### ISSUE TITLE
Fix Azure OAuth verification proccess for prod env

### ISSUE THREAD

**Issue by darashevcstbg** [Daiteap/daiteap-platform#6]
It is not working for users which are not added as external users.

**Comment by darashevcstbg** [comment]
![Screenshot_20230606_172222](https://github.com/Daiteap/daiteap-platform/assets/72433964/ad00ba84-1633-4c3d-92d7-77d46dce693f)

Still not working after adding the user as external user

**Comment by darashevcstbg** [comment]
https://learn.microsoft.com/en-us/azure/active-directory/develop/permissions-consent-overview

**Comment by darashevcstbg** [comment]
- we call /common/adminconsent' endpoint which is not needed
- we should use /common/oauth2 instead of /{tenant}/oauth2 endpoints
- from this comment https://github.com/MicrosoftDocs/azure-docs/issues/38467#issuecomment-529304890 and my tests, we can use only v1 /token endpoint to get token which we can use to get all user tenants

**Comment by darashevcstbg** [comment]
I'm currently experiencing an issue while trying to authenticate personal Microsoft accounts with Azure App Registration via Microsoft's OAuth 2.0 endpoint (v1.0). I'm trying to list all tenants associated with personal Microsoft accounts through this endpoint.

My understanding from this thread (https://github.com/MicrosoftDocs/azure-docs/issues/38467#issuecomment-529304890) is that listing all tenants for personal users is not supported with the OAuth 2.0 endpoint (v2.0) for the resource "https://management.azure.com/" within a multi-tenant application context.

The Azure App Registration is configured to accept "Accounts in any organizational directory (Any Azure AD directory - Multitenant)" and "personal Microsoft accounts (e.g., Skype, Xbox)". However, when I attempt to authenticate a personal account, I encounter the following error:

AADSTS500200: User account 'USER_ACCOUNT' is a personal Microsoft account. Personal Microsoft accounts are not supported for this application unless explicitly invited to an organization. Try signing out and signing back in with an organizational account.

**Comment by darashevcstbg** [comment]
After speaking with Azure Support, it has been confirmed that the only way to successfully authenticate with a personal Microsoft account through the OAuth 2.0 endpoint (v1.0) for a multi-tenant app is to invite each personal account as a guest user to the tenant.
 
You can refer to this tutorial: https://learn.microsoft.com/en-us/troubleshoot/azure/active-directory/error-code-aadsts50020-user-account-identity-provider-does-not-exist. The key step is in "Cause 4: Guest user wasn't invited".

**Comment by darashev-daiteap** [comment]
Here is the proposed process for credentials creation for microsoft accounts:

1. **Start Process:** The user starts the OAuth process by clicking the 'OAuth' button on the Daiteap platform.

2. **Information Message:** We can provide information to the user that if they have a personal Microsoft account that is not associated with an Azure organization, they need to receive an invitation to join the Daiteap Azure tenant as a guest. We could have a checkbox or similar UI element where they can indicate that they have a personal account.

3. **User Decision:** If the user identifies their account as a personal account (by checking the box or another UI indicator), they can click a 'Request Invitation' button which will trigger the platform to send an invitation to their email.

4. **Accepting Invitation:** The user is then instructed to check their email and accept the invitation. 

5. **Continue OAuth:** After accepting the invitation, they can return to the Daiteap platform and click the 'Continue OAuth' button to complete the OAuth process.

**Comment by darashevcstbg** [comment]
Here is the proposed process for credentials creation for microsoft accounts:

1. **Start Process:** The user starts the OAuth process by clicking the 'OAuth' button on the Daiteap platform.

2. **Information Message:** We can provide information to the user that if they have a personal Microsoft account that is not associated with an Azure organization, they need to receive an invitation to join the Daiteap Azure tenant as a guest. We could have a checkbox or similar UI element where they can indicate that they have a personal account.

3. **User Decision:** If the user identifies their account as a personal account (by checking the box or another UI indicator), they can click a 'Request Invitation' button which will trigger the platform to send an invitation to their email.

4. **Accepting Invitation:** The user is then instructed to check their email and accept the invitation. 

5. **Continue OAuth:** After accepting the invitation, they can return to the Daiteap platform and click the 'Continue OAuth' button to complete the OAuth process.
