### ISSUE TITLE
Automate daiteap development environment

### ISSUE THREAD

**Issue by vikig07** [Daiteap/daiteap-platform#7]
Current setup:
- automated local platform deployment with docker-compose

Pros:
- fully automated local setup
- well documented

Cons:
- unrealistic deployment (production uses Kubernetes cluster instead of docker-compose)
- hard development/debugging - do not describe how to run and configure services locally (daiteap-ui)

![Daiteap-dev-setup](https://github.com/Daiteap/daiteap-platform/assets/117808703/5e21ebfa-da4b-4aed-8da1-4eeef2a0b69f)

Tasks:
- [x] deploy local environment using devcontainer and KIND cluster
- [x] install and configure ArgoCD
- [x] create repos in ArgoCD
- [x] create applications in ArgoCD
- [x] Modify HELM charts to always use Daiteap public images
- [x] Modify ArgoCD repos to point to public daiteap repos in github.com
- [x] Remove Credentials steps from README-devcontainer-auto.md, because they are not needed. Everything for the deployment is public.
- [x] Update `master` branchs on public github repositories for daiteap to be up-to-date with versions in gitlab.cst-bg.net
- [x] Use Github Actions to automatically build and publish docker images to github Container Registry. Update all references in the deployment to point to the new images in github.com
- [x] Use public helm charts for dependent components keycloak, mysql, redis, rabitmqbroker, vault. Fix the versions of public components.
- [x] Copy nfs_server and mysql charts to github platform repo.
- [x] Clear all "cst" from repo files.
- [x] sync applications in ArgoCD
- [x] configure and init daiteap platform
- [x] document how to debug individual modules with telepresence
- [x] add instructions how to start front-end and back-end locally

**Comment by vikig07** [comment]
https://github.com/Daiteap/daiteap-ui/pull/3

https://github.com/Daiteap/daiteap-platform/pull/9

**Comment by darashevcstbg** [comment]
Keycloak setup steps can be automated.

**Comment by darashevcstbg** [comment]
After restarting VS code, the vault is locked, and port forward is missing. There is no documentation how to fix it.

**Comment by ignatov17** [comment]
The script ./scripts/init-cluster.sh brakes on command at line 66 with error:

---- Waiting For DB Pod ----
pod/database-9bb8777cc-g54mq condition met
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
command terminated with exit code 1

**Comment by ignatov17** [comment]
The script ./scripts/init-cluster.sh brakes on command at line 66 with error:

---- Waiting For DB Pod ----
pod/database-9bb8777cc-g54mq condition met
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
command terminated with exit code 1

**Comment by vikig07** [comment]
#11
